/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WelcomeScreen;

import DatabaseConnectivity.connectivity;
import com.sun.jdi.connect.spi.Connection;
import erp.login.login;
import java.awt.Color;
import static java.awt.SystemColor.window;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Muneeb Ahmad
 */
public class WcScr extends javax.swing.JFrame {

    ImageIcon icon = new ImageIcon("/images/icons8_shutdown_24px.png");  
   
    
    /**
     * Creates new form WcScr
     */
    public WcScr() throws SQLException {
        initComponents();
        System.out.println("Statsinf gSonnction:");
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingBar = new javax.swing.JProgressBar();
        loadingdesp = new javax.swing.JLabel();
        loadingValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(232, 1, 1));
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingBar.setBackground(new java.awt.Color(255, 255, 255));
        loadingBar.setForeground(new java.awt.Color(255, 51, 51));
        loadingBar.setBorder(null);
        loadingBar.setBorderPainted(false);
        getContentPane().add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 390, 800, 20));

        loadingdesp.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        loadingdesp.setForeground(new java.awt.Color(255, 255, 255));
        loadingdesp.setText("Loading...");
        getContentPane().add(loadingdesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        loadingValue.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        loadingValue.setForeground(new java.awt.Color(255, 255, 255));
        loadingValue.setText("0 %");
        getContentPane().add(loadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wcbg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(722, 397));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            WcScr wc = new WcScr();
        } catch (SQLException ex) {
            Logger.getLogger(WcScr.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_formWindowOpened

    /**
     * @param arg
     */
    public static void main() throws SQLException {

        WcScr wc = new WcScr();
        wc.setVisible(true);
        System.out.println("setVisible1");
        try {

            for (int i = 0; i <= 100; i++) {

                Thread.sleep(100);
                wc.loadingValue.setText(i + "%");

                if (i == 10) {
                    System.out.println("setVisible2");
                    wc.loadingdesp.setText("Turning on Modules...");
                }
                if (i == 20) {
                    wc.loadingdesp.setText("Loading Modules...");
                }
                if (i == 50) {
                    wc.loadingdesp.setText("Connecting to Database...");
                    connectivity con = null;
                    con = new connectivity();
                    if(con.chk_conn==0)
                    {
                        
                    }
                    else
                    {
                    System.out.println("Con is: " + con);  
                    wc.loadingdesp.setText("Connecting to Database... Error !!!");
                    wc.loadingdesp.setForeground(Color.red);
                    JOptionPane.showMessageDialog(null, "Database is no connected!!!");
                    
                    
                    Thread. sleep(2000);
                    wc.dispose();
                    break;
                    }
                    

                }
                if (i == 70) {
                    wc.loadingdesp.setText("Connection Successful ");
                }
                if (i == 80) {
                    wc.loadingdesp.setText("Launching Application...");
                }
                if (i == 100) {
                    wc.dispose();
                    login obj = new login();
                    obj.setVisible(true);
                }
                wc.loadingBar.setValue(i);

            }
        } catch (InterruptedException e) {

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel loadingValue;
    private javax.swing.JLabel loadingdesp;
    // End of variables declaration//GEN-END:variables

}
