/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin_Dashboard;

import DatabaseConnectivity.connectivity;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.util.Random;
import javax.imageio.ImageIO;

/**
 *
 * @author Muneeb Ahmad
 */
public class Add_faculity extends javax.swing.JFrame {

    ResultSet myres = null;
    connectivity conn;
    String filename = null;
    String DeptId = null;
    String staffID = null;
    FileInputStream fis = null;
    int chk_img = 0;
    String Fac_ID_main = null;

    int UserID = 0;

    String up_Name = null;
    String up_fName = null;
    String up_lName = null;
    String up_email = null;
    String up_Number = null;
    String up_Dob = null;
    String up_Gender = null;
    String up_State = null;
    String up_City = null;
    String up_Qual = null;
    String up_Exp = null;
    String up_Pos = null;
    String up_Dept = null;

    InputStream input;
    FileOutputStream output;
    File theFile = new File("UserImg.png");

    /**
     * Creates new form Add_Department
     */
    public Add_faculity() {
        initComponents();
        this.conn = new connectivity();
        fetchDept();
        kButton2.setVisible(false);

    }

    Add_faculity(String Fac_Id) throws FileNotFoundException {
        initComponents();
        this.conn = new connectivity();
        Fac_ID_main = Fac_Id;
        Id1.setText(Fac_Id.replaceAll("\\s", ""));
        System.out.println("FAc Is is: " + Fac_ID_main);
        Id1.setEditable(false);
        jLabel1.setText("Update Faculity");
        kButton1.setText("Update Faculity");
        kButton2.setVisible(true);
        fetchuserDetails();
        fetchDept();

        //Dept.getModel().setSelectedItem();
        NAme.setText(up_Name);
        email.setText(up_email);
        Number.setText(up_Number);
        Gender.getModel().setSelectedItem(up_Gender);
        City.setText(up_City);
        State.setText(up_State);
        //jDateChooser1.setDateFormatString(up_Dob);
        //jDateChooser1.setEnabled(false);
        Qualification.setText(up_Qual);
        Exp.setText(up_Exp);
        Position.getModel().setSelectedItem(up_Pos);

        Dept.setEnabled(false);

        byte buffer[] = new byte[1024];
        System.out.println("Buffer is : " + buffer);
        output = new FileOutputStream(theFile);
        try {
            while (input.read(buffer) > 0) {
                output.write(buffer);
            }
        } catch (IOException ex) {
            Logger.getLogger(Add_faculity.class.getName()).log(Level.SEVERE, null, ex);
        }
        String path = theFile.getAbsolutePath();
        System.out.println("output is : " + output);
        ImageIcon myimage = new ImageIcon(path);
        System.out.println("Myimage is : " + myimage);
        Image img = myimage.getImage();
        Image newImage = img.getScaledInstance(159, 159, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        PimgX.setIcon(image);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        maximize = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Gender = new javax.swing.JComboBox<>();
        kButton1 = new com.k33ptoo.components.KButton();
        NAme = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        State = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Number = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Qualification = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Exp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        PimgX = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Id1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Position = new javax.swing.JComboBox<>();
        Dept = new javax.swing.JComboBox<>();
        Dept_err = new javax.swing.JLabel();
        Dept_err1 = new javax.swing.JLabel();
        Dept_err2 = new javax.swing.JLabel();
        Dept_err4 = new javax.swing.JLabel();
        Dept_err5 = new javax.swing.JLabel();
        Dept_err6 = new javax.swing.JLabel();
        Dept_err7 = new javax.swing.JLabel();
        Dept_err8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        valid = new javax.swing.JLabel();
        valid1 = new javax.swing.JLabel();
        valid2 = new javax.swing.JLabel();
        valid3 = new javax.swing.JLabel();
        valid4 = new javax.swing.JLabel();
        valid5 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 51, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 51, 51));
        kGradientPanel1.setOpaque(false);

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD NEW FACULITY");

        maximize.setForeground(new java.awt.Color(204, 204, 204));
        maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_white.png"))); // NOI18N
        maximize.setIconTextGap(14);
        maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maximizeMouseExited(evt);
            }
        });

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_white.png"))); // NOI18N
        minimize.setIconTextGap(14);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_white.png"))); // NOI18N
        close.setIconTextGap(14);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maximize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minimize)
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maximize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Department");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");

        Gender.setBackground(new java.awt.Color(51, 51, 51));
        Gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Others" }));
        Gender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Gender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GenderMouseEntered(evt);
            }
        });
        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });

        kButton1.setText("Add Fauulity");
        kButton1.setkBackGroundColor(new java.awt.Color(204, 204, 204));
        kButton1.setkEndColor(new java.awt.Color(204, 204, 204));
        kButton1.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        kButton1.setkStartColor(new java.awt.Color(51, 51, 51));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        NAme.setBackground(new java.awt.Color(51, 51, 51));
        NAme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NAme.setForeground(new java.awt.Color(255, 255, 255));
        NAme.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        NAme.setCaretColor(new java.awt.Color(255, 255, 255));
        NAme.setOpaque(true);
        NAme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NAmeFocusLost(evt);
            }
        });
        NAme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAmeActionPerformed(evt);
            }
        });
        NAme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NAmeKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Faculity Name");

        State.setBackground(new java.awt.Color(51, 51, 51));
        State.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        State.setForeground(new java.awt.Color(255, 255, 255));
        State.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        State.setCaretColor(new java.awt.Color(255, 255, 255));
        State.setOpaque(true);
        State.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                StateKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("State");

        City.setBackground(new java.awt.Color(51, 51, 51));
        City.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        City.setForeground(new java.awt.Color(255, 255, 255));
        City.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        City.setCaretColor(new java.awt.Color(255, 255, 255));
        City.setOpaque(true);
        City.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CityKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("City");

        email.setBackground(new java.awt.Color(51, 51, 51));
        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        email.setCaretColor(new java.awt.Color(255, 255, 255));
        email.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email Adress");

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contact Number");

        Number.setBackground(new java.awt.Color(51, 51, 51));
        Number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Number.setForeground(new java.awt.Color(255, 255, 255));
        Number.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        Number.setCaretColor(new java.awt.Color(255, 255, 255));
        Number.setOpaque(true);
        Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NumberKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Qualification");

        Qualification.setBackground(new java.awt.Color(51, 51, 51));
        Qualification.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Qualification.setForeground(new java.awt.Color(255, 255, 255));
        Qualification.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        Qualification.setCaretColor(new java.awt.Color(255, 255, 255));
        Qualification.setOpaque(true);
        Qualification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QualificationKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Experience");

        Exp.setBackground(new java.awt.Color(51, 51, 51));
        Exp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Exp.setForeground(new java.awt.Color(255, 255, 255));
        Exp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        Exp.setCaretColor(new java.awt.Color(255, 255, 255));
        Exp.setOpaque(true);
        Exp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ExpKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date Of Birth");

        PimgX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_male_user_150px_1.png"))); // NOI18N
        PimgX.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jButton1.setText("Choose Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Id1.setEditable(false);
        Id1.setBackground(new java.awt.Color(51, 51, 51));
        Id1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Id1.setForeground(new java.awt.Color(255, 255, 255));
        Id1.setText("Auto Generated");
        Id1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        Id1.setCaretColor(new java.awt.Color(255, 255, 255));
        Id1.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Faculity ID");

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Position");

        Position.setBackground(new java.awt.Color(51, 51, 51));
        Position.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Full Professor", "Associate Professor", "Assistant Professor", "Lectrar", "Lab Assistant" }));
        Position.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Position.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PositionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PositionMouseEntered(evt);
            }
        });
        Position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PositionActionPerformed(evt);
            }
        });

        Dept.setBackground(new java.awt.Color(51, 51, 51));
        Dept.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        Dept.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Dept.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DeptItemStateChanged(evt);
            }
        });
        Dept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeptMouseEntered(evt);
            }
        });
        Dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptActionPerformed(evt);
            }
        });

        Dept_err.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Dept_err.setForeground(new java.awt.Color(255, 0, 51));
        Dept_err.setText("[Mandatory]");

        Dept_err1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Dept_err1.setForeground(new java.awt.Color(255, 0, 51));
        Dept_err1.setText("[Mandatory]");

        Dept_err2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Dept_err2.setForeground(new java.awt.Color(255, 0, 51));
        Dept_err2.setText("[Mandatory]");

        Dept_err4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Dept_err4.setForeground(new java.awt.Color(255, 0, 51));
        Dept_err4.setText("[Mandatory]");

        Dept_err5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Dept_err5.setForeground(new java.awt.Color(255, 0, 51));
        Dept_err5.setText("[Mandatory]");

        Dept_err6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Dept_err6.setForeground(new java.awt.Color(255, 0, 51));
        Dept_err6.setText("[Mandatory]");

        Dept_err7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Dept_err7.setForeground(new java.awt.Color(255, 0, 51));
        Dept_err7.setText("[Mandatory]");

        Dept_err8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Dept_err8.setForeground(new java.awt.Color(255, 0, 51));
        Dept_err8.setText("[Mandatory]");

        jDateChooser1.setBackground(new java.awt.Color(51, 51, 51));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));

        kButton2.setText("Delete Faculity");
        kButton2.setkBackGroundColor(new java.awt.Color(204, 204, 204));
        kButton2.setkEndColor(new java.awt.Color(255, 0, 51));
        kButton2.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        kButton2.setkStartColor(new java.awt.Color(51, 51, 51));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NAme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(4, 4, 4)
                                .addComponent(valid, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dept_err2)))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(Dept_err))
                                        .addComponent(State, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                        .addComponent(email)
                                        .addComponent(jLabel9)
                                        .addComponent(Qualification)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(9, 9, 9)
                                            .addComponent(valid4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Dept_err7))
                                        .addComponent(jLabel13))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(8, 8, 8)
                                        .addComponent(valid1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dept_err4)))
                                .addGap(18, 18, 18))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(Dept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(21, 21, 21)))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(9, 9, 9)
                                        .addComponent(valid2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dept_err5))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(7, 7, 7)
                                        .addComponent(valid3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dept_err6))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(10, 10, 10)
                                        .addComponent(valid5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dept_err8))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(Dept_err1))
                                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Exp, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Number, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Id1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                        .addComponent(City, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(PimgX, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Dept_err))
                        .addGap(12, 12, 12)
                        .addComponent(Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Dept_err1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Id1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(Dept_err2))
                            .addComponent(valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NAme, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(9, 9, 9)
                        .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(Dept_err4))
                            .addComponent(valid1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(Dept_err5))
                            .addComponent(valid2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(Dept_err6))
                            .addComponent(valid3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(Dept_err7))
                            .addComponent(valid4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Qualification, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(Dept_err8))
                            .addComponent(valid5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(PimgX, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(692, 765));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void fetchuserDetails() {
        try {
            myres = conn.mystmt.executeQuery("select * from staff join person on staff.USERID=person.USERID where STAFF_ID = '" + Fac_ID_main + "'");
            while (myres.next()) {
                UserID = Integer.parseInt(myres.getString("USERID"));
                System.out.println("Fetching . . .. . . . .. .");
                up_Name = myres.getString("NAME");
                up_email = myres.getString("Email");
                up_Number = myres.getString("MOBILE_NO");
                up_Dob = myres.getString("DOB");
                up_Gender = myres.getString("Gender");
                up_State = myres.getString("MOBILE_NO");
                up_City = myres.getString("CITY");
                up_Qual = myres.getString("QUALIFICATION");
                up_Exp = myres.getString("EXPERIENCE");
                up_Pos = myres.getString("POSITION");
                input = myres.getBinaryStream("PROFILE_PIC");

                System.out.println("Date is: " + up_Dob);

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void fetchDept() {

        try {
            myres = conn.mystmt.executeQuery("select * from department");
            if (myres.getRow() <= 0) {
                int sr = 0;
                System.out.println("Fetching...");
                while (myres.next()) {
                    Dept.addItem(myres.getString("DEPARTMENT_NAME"));
                    System.out.println(myres.getString("DEPARTMENT_NAME"));
                }
            } else {
                System.out.println("No Record Found");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        if (filename == null) {
            filename = "C:\\Users\\Muneeb Ahmad\\Documents\\NetBeansProjects\\ERP\\ERP\\src\\images\\Demo_Profile.png";
        } 
        if (Id1.getText().equals("Auto Generated") || Position.getSelectedItem().equals("Select") || NAme.getText().equals(null) || State.getText().equals(null) || City.getText().equals(null) || jDateChooser1 == null) {
            JOptionPane.showMessageDialog(null, "Fill All Data Please!");
        } else {
            if (valid == null || valid1 == null || valid2 == null || valid3 == null || valid4 == null || valid5 == null) {
                JOptionPane.showMessageDialog(null, "Fill All Data Please!");
            } else {
                String Fal_ID = Id1.getText();
                String Name = NAme.getText();
                String Satte = State.getText();
                String Cityy = City.getText();
                String Address = Satte + " " + Cityy;
                String Number1 = this.Number.getText();
                String Email = Name + "@hogwards.com";
                String Quali = Qualification.getText();
                String Exper = Exp.getText();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String dateof = sdf.format(jDateChooser1.getDate());
                System.out.println("date of birth is: " + dateof);
                String Password = "faculity123";
                String Gender1 = (String) this.Gender.getSelectedItem();
                String Role = "Teacher";
                String Position1 = (String) Position.getSelectedItem();
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                LocalDateTime JoinDate = LocalDateTime.now();
                try {
                    int result = 0;
                    System.out.println("Chk Image is: " + chk_img);

                    fis = new FileInputStream(filename);

                    System.out.println("filename is: " + filename);
                    System.out.println("Fis is: " + fis);

                    System.out.println("click 1");
                    System.out.println("User id is: " + UserID);
                    System.out.println("FAc id is: " + Fac_ID_main);
                    String query = "update person set NAME='" + Name + "', MOBILE_NO='" + Number1 + "', CITY='" + Cityy + "',Email = '" + Email + "',STATE = '" + Satte + "' ,ADDRESS = '" + Address + "',DOB = '" + dateof + "' ,Gender = '" + Gender1 + "' where USERID='" + UserID + "'";
                    PreparedStatement pr = conn.myconn.prepareStatement(query);
                    result = pr.executeUpdate();
                    if (chk_img==1) {
                        query = "update staff set QUALIFICATION='" + Quali + "', EXPERIENCE='" + Exper + "', POSITION='" + Position1 + "' , PROFILE_PIC = ? where STAFF_ID='" + Fac_ID_main + "'";
                    pr = conn.myconn.prepareStatement(query);
                    pr.setBinaryStream(1, fis);
                    } else {
                        query = "update staff set QUALIFICATION='" + Quali + "', EXPERIENCE='" + Exper + "', POSITION='" + Position1 + "' where STAFF_ID='" + Fac_ID_main + "'";
                        pr = conn.myconn.prepareStatement(query);
                    }
                    
                    result = pr.executeUpdate();
                    System.out.println("addStudentTheoryMarks --> Update" + result);
                    if (result == 0) {
                        myres = conn.mystmt.executeQuery("select * from person");
                        int sr = 0;
                        while (myres.next()) {
                            sr++;
                        }
                        int userID = 100 + sr + 1;
                        System.out.println("User id is: +" + userID);
                        query = "insert into Person values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
                        pr = conn.myconn.prepareStatement(query);
                        pr.setInt(1, userID);
                        pr.setString(2, Name);
                        pr.setString(3, Number1);
                        pr.setString(4, Cityy);
                        pr.setString(5, Email);
                        pr.setString(6, Password);
                        pr.setString(7, Satte);
                        pr.setString(8, Address);
                        pr.setString(9, dateof);
                        pr.setString(10, Gender1);
                        pr.setString(11, Role);
                        pr.setString(12, null);
                        pr.setString(13, null);
                        pr.executeUpdate();

                        myres = conn.mystmt.executeQuery("select * from staff");
                        sr = 0;
                        while (myres.next()) {
                            sr++;
                        }
                        String query1 = "insert into staff values(?,?,?,?,?,?,?,?)";
                        PreparedStatement pr1 = conn.myconn.prepareStatement(query1);
                        pr1.setString(1, staffID);
                        pr1.setInt(2, userID);
                        pr1.setString(3, DeptId);
                        pr1.setString(4, JoinDate.toString());
                        pr1.setString(5, Quali);
                        pr1.setString(6, Exper);
                        pr1.setBinaryStream(7, fis);
                        pr1.setString(8, Position1);
                        pr1.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Member Added Successfully");
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Member Update Successfully");

                        this.dispose();
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Assigning_subject.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "SomeThing Went Wrong!");
                } catch (NullPointerException ex) {
                    Logger.getLogger(Add_student.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Fill All Data Please!");
                } catch (IllegalArgumentException ex) {
                    Logger.getLogger(Add_student.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Enter valid Data!");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Add_faculity.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }

    }//GEN-LAST:event_kButton1ActionPerformed

    private void GenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenderMouseEntered

    }//GEN-LAST:event_GenderMouseEntered

    private void GenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenderMouseClicked

    }//GEN-LAST:event_GenderMouseClicked

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_white.png")));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_red.png")));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked

        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_white.png")));
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_yellow.png")));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void maximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseExited
        maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_white.png")));
    }//GEN-LAST:event_maximizeMouseExited

    private void maximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseEntered
        maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_blue.png")));
    }//GEN-LAST:event_maximizeMouseEntered

    private void maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseClicked
        int state = this.getExtendedState();

        if (state == 0) {
            //            this.setExtendedState(Frame.MAXIMIZED_BOTH);
        } else {
            // this.setExtendedState(Frame.NORMAL);
        }
    }//GEN-LAST:event_maximizeMouseClicked

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
chk_img++;
        File file = chooser.getSelectedFile();
        filename = file.getAbsolutePath();
        System.out.println("Absolute path is: "+filename);
        BufferedImage bufferedImage = null;

        try {
            bufferedImage = ImageIO.read(new File(filename));

        } catch (IOException e) {
            e.printStackTrace();
        }

        Image scaledImage = bufferedImage.getScaledInstance(PimgX.getWidth(), PimgX.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(scaledImage);
        PimgX.setIcon(image);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NAmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAmeActionPerformed

    }//GEN-LAST:event_NAmeActionPerformed

    private void NAmeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NAmeFocusLost
        Random x = new Random();
        int n = x.nextInt(1000);//random number 1-100
        if (!NAme.getText().equals(""))

            email.setText(NAme.getText().toLowerCase().replaceAll("\\s", "") + n + "@Hogwards.com");
    }//GEN-LAST:event_NAmeFocusLost

    private void PositionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PositionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PositionMouseClicked

    private void PositionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PositionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PositionMouseEntered

    private void PositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PositionActionPerformed

    private void DeptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeptMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DeptMouseClicked

    private void DeptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeptMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DeptMouseEntered

    private void DeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeptActionPerformed

    private void DeptItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DeptItemStateChanged

        String Deptname = (String) Dept.getSelectedItem();

        try {
            myres = conn.mystmt.executeQuery("select * from department where DEPARTMENT_NAME = '" + Deptname + "'");

            while (myres.next()) {
                DeptId = myres.getString("DEPT_CODE");
            }
            myres = conn.mystmt.executeQuery("select * from staff");
            int sr = 0;
            while (myres.next()) {
                sr++;
            }
            int sr1 = sr + 100 + 1;
            staffID = DeptId + "-" + sr1;
            Id1.setText(staffID);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_DeptItemStateChanged

    private void NAmeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NAmeKeyReleased
        if (NAme.getText().matches("[a-zA-Z_\\s]+")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            valid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            valid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_NAmeKeyReleased

    private void StateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StateKeyReleased
        if (State.getText().matches("[a-zA-Z_]+")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            valid1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            valid1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_StateKeyReleased

    private void CityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CityKeyReleased
        if (City.getText().matches("[a-zA-Z_]+")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            valid2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            valid2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_CityKeyReleased

    private void NumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumberKeyReleased
        if (Number.getText().matches("[0-9]+")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            valid3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            valid3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_NumberKeyReleased

    private void QualificationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QualificationKeyReleased
        if (Qualification.getText().matches("[a-zA-Z_]+")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            valid4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            valid4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_QualificationKeyReleased

    private void ExpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ExpKeyReleased
        if (Exp.getText().matches("[0-9]+")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            valid5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            valid5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_ExpKeyReleased

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed

        try {
            System.out.println("User Id : " + UserID);
            String query = "delete from staff where USERID='" + UserID + "'";
            PreparedStatement pr = conn.myconn.prepareStatement(query);
            pr.executeUpdate();
            JOptionPane.showMessageDialog(null, "Member Deleted Successfully");
            this.dispose();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Something Went Wrong");
        }
    }//GEN-LAST:event_kButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_faculity.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_faculity.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_faculity.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_faculity.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            System.err.println("Error: " + e.getMessage());
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Add_faculity().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField City;
    private javax.swing.JComboBox<String> Dept;
    private javax.swing.JLabel Dept_err;
    private javax.swing.JLabel Dept_err1;
    private javax.swing.JLabel Dept_err2;
    private javax.swing.JLabel Dept_err4;
    private javax.swing.JLabel Dept_err5;
    private javax.swing.JLabel Dept_err6;
    private javax.swing.JLabel Dept_err7;
    private javax.swing.JLabel Dept_err8;
    private javax.swing.JTextField Exp;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField Id1;
    private javax.swing.JTextField NAme;
    private javax.swing.JTextField Number;
    private javax.swing.JLabel PimgX;
    private javax.swing.JComboBox<String> Position;
    private javax.swing.JTextField Qualification;
    private javax.swing.JTextField State;
    private javax.swing.JLabel close;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel maximize;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel valid;
    private javax.swing.JLabel valid1;
    private javax.swing.JLabel valid2;
    private javax.swing.JLabel valid3;
    private javax.swing.JLabel valid4;
    private javax.swing.JLabel valid5;
    // End of variables declaration//GEN-END:variables
}
