/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin_Dashboard;

import DatabaseConnectivity.connectivity;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muneeb Ahmad
 */
public class Add_student extends javax.swing.JFrame {

    ResultSet myres = null;
    ResultSet myres1 = null;
    ResultSet myres2 = null;
    String filename = null;
    String STUDENT_ID_main = "asd";
    String Deptcode = "qwe";
    int UserID = 0;
    String Option_subject = null;
    FileInputStream fis = null;
    connectivity conn;

    String up_Name = null;
    String up_fName = null;
    String up_lName = null;
    String up_email = null;
    String up_Number = null;
    String up_Dob = null;
    String up_Gender = null;
    String up_State = null;
    String up_City = null;
    String up_fat_name = null;
    String up_fat_Occ = null;
    String up_Sem = null;
    String up_Opt_Sub = null;
    int chk_img = 0;

    InputStream input;
    FileOutputStream output;
    File theFile = new File("UserImg.png");

    /**
     * Creates new form Add_Department
     */
    public Add_student() {
        initComponents();
        this.conn = new connectivity();
        kButton1.setFont(new Font("Arial", Font.BOLD, 14));
        fetchDept();
        kButton2.setVisible(false);

    }

    Add_student(String Stud_Id, String DeptName) throws FileNotFoundException {
        initComponents();

        this.conn = new connectivity();
        STUDENT_ID_main = Stud_Id;
        StudentID.setText(Stud_Id.replaceAll("\\s", ""));
        Dept.getModel().setSelectedItem(DeptName);
        StudentID.setEditable(false);
        jLabel1.setText("Update Student");
        kButton1.setText("Update Student");
        kButton2.setVisible(true);
        fetchuserDetails();
        fetchDept();

        String[] tokens = up_Name.split(" ");
        fname.setText(tokens[0]);
        Lname.setText(tokens[1]);
        email.setText(up_email);
        Number.setText(up_Number);
        Gender.getModel().setSelectedItem(up_Gender);
        City.setText(up_City);
        State.setText(up_State);
        jDateChooser1.setDateFormatString(up_Dob);
        //jDateChooser1.setEnabled(false);
        fatherName.setText(up_fat_name);
        FatherOccupation.setText(up_fat_Occ);
        Semester.getModel().setSelectedItem(up_Sem);
        Semester.setEnabled(false);
        Dept.setEnabled(false);
        Opt_sub.getModel().setSelectedItem(up_Opt_Sub);

        byte buffer[] = new byte[1024];
        System.out.println("Buffer is : " + buffer);
        output = new FileOutputStream(theFile);
        try {
            while (input.read(buffer) > 0) {
                output.write(buffer);
            }
        } catch (IOException ex) {
            Logger.getLogger(Add_faculity.class.getName()).log(Level.SEVERE, null, ex);
        }
        String path = theFile.getAbsolutePath();
        System.out.println("output is : " + output);
        ImageIcon myimage = new ImageIcon(path);
        System.out.println("Myimage is : " + myimage);
        Image img = myimage.getImage();
        Image newImage = img.getScaledInstance(159, 159, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        PimgX.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        maximize = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Dept = new javax.swing.JComboBox<>();
        kButton1 = new com.k33ptoo.components.KButton();
        StudentID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        PimgX = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Semester = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Opt_sub = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Lname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Number = new javax.swing.JTextField();
        Gender = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        State = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        fatherName = new javax.swing.JTextField();
        FatherOccupation = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        Dept_err = new javax.swing.JLabel();
        Sem_err = new javax.swing.JLabel();
        Fname_err = new javax.swing.JLabel();
        LName_err = new javax.swing.JLabel();
        Num_err = new javax.swing.JLabel();
        Dob_err = new javax.swing.JLabel();
        Gender_err = new javax.swing.JLabel();
        State_err = new javax.swing.JLabel();
        City_err = new javax.swing.JLabel();
        FAtherName_err = new javax.swing.JLabel();
        FatOcc_err = new javax.swing.JLabel();
        valid = new javax.swing.JLabel();
        valid1 = new javax.swing.JLabel();
        valid2 = new javax.swing.JLabel();
        valid3 = new javax.swing.JLabel();
        valid4 = new javax.swing.JLabel();
        valid5 = new javax.swing.JLabel();
        valid6 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 51, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 51, 51));
        kGradientPanel1.setOpaque(false);

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD NEW STUDENT");

        maximize.setForeground(new java.awt.Color(204, 204, 204));
        maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_white.png"))); // NOI18N
        maximize.setIconTextGap(14);
        maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maximizeMouseExited(evt);
            }
        });

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_white.png"))); // NOI18N
        minimize.setIconTextGap(14);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_white.png"))); // NOI18N
        close.setIconTextGap(14);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maximize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minimize)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maximize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Select Department");

        Dept.setBackground(new java.awt.Color(51, 51, 51));
        Dept.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Dept.setForeground(new java.awt.Color(255, 255, 255));
        Dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        Dept.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Dept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeptMouseEntered(evt);
            }
        });
        Dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptActionPerformed(evt);
            }
        });

        kButton1.setText("Add Student");
        kButton1.setkBackGroundColor(new java.awt.Color(255, 0, 0));
        kButton1.setkEndColor(new java.awt.Color(204, 204, 204));
        kButton1.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        kButton1.setkStartColor(new java.awt.Color(51, 51, 51));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        StudentID.setEditable(false);
        StudentID.setBackground(new java.awt.Color(51, 51, 51));
        StudentID.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        StudentID.setForeground(new java.awt.Color(255, 255, 255));
        StudentID.setText("Auto Generated");
        StudentID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        StudentID.setCaretColor(new java.awt.Color(255, 255, 255));
        StudentID.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Student ID");

        fname.setBackground(new java.awt.Color(51, 51, 51));
        fname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        fname.setCaretColor(new java.awt.Color(255, 255, 255));
        fname.setOpaque(true);
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnameKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("First Name");

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email ID");

        email.setEditable(false);
        email.setBackground(new java.awt.Color(51, 51, 51));
        email.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Auto Generated");
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        email.setCaretColor(new java.awt.Color(255, 255, 255));
        email.setOpaque(true);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date Of Birth");

        PimgX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_male_user_150px_1.png"))); // NOI18N
        PimgX.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jButton1.setText("Choose Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Semester.setBackground(new java.awt.Color(51, 51, 51));
        Semester.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Semester.setForeground(new java.awt.Color(255, 255, 255));
        Semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Others" }));
        Semester.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Semester.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SemesterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SemesterMouseEntered(evt);
            }
        });
        Semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemesterActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Select Semester");

        Opt_sub.setBackground(new java.awt.Color(51, 51, 51));
        Opt_sub.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Opt_sub.setForeground(new java.awt.Color(255, 255, 255));
        Opt_sub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        Opt_sub.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Opt_sub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Opt_subMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Opt_subMouseEntered(evt);
            }
        });
        Opt_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opt_subActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Select Optional Subject");

        Lname.setBackground(new java.awt.Color(51, 51, 51));
        Lname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lname.setForeground(new java.awt.Color(255, 255, 255));
        Lname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        Lname.setCaretColor(new java.awt.Color(255, 255, 255));
        Lname.setOpaque(true);
        Lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                LnameFocusLost(evt);
            }
        });
        Lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LnameKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Last Name");

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Contact Number");

        Number.setBackground(new java.awt.Color(51, 51, 51));
        Number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Number.setForeground(new java.awt.Color(255, 255, 255));
        Number.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        Number.setCaretColor(new java.awt.Color(255, 255, 255));
        Number.setOpaque(true);
        Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NumberKeyReleased(evt);
            }
        });

        Gender.setBackground(new java.awt.Color(51, 51, 51));
        Gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Gender.setForeground(new java.awt.Color(255, 255, 255));
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Others" }));
        Gender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Gender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GenderMouseEntered(evt);
            }
        });
        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gender");

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("State");

        State.setBackground(new java.awt.Color(51, 51, 51));
        State.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        State.setForeground(new java.awt.Color(255, 255, 255));
        State.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        State.setCaretColor(new java.awt.Color(255, 255, 255));
        State.setOpaque(true);
        State.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                StateKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("City");

        City.setBackground(new java.awt.Color(51, 51, 51));
        City.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        City.setForeground(new java.awt.Color(255, 255, 255));
        City.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        City.setCaretColor(new java.awt.Color(255, 255, 255));
        City.setOpaque(true);
        City.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CityKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Father Name");

        fatherName.setBackground(new java.awt.Color(51, 51, 51));
        fatherName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fatherName.setForeground(new java.awt.Color(255, 255, 255));
        fatherName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        fatherName.setCaretColor(new java.awt.Color(255, 255, 255));
        fatherName.setOpaque(true);
        fatherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fatherNameKeyReleased(evt);
            }
        });

        FatherOccupation.setBackground(new java.awt.Color(51, 51, 51));
        FatherOccupation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FatherOccupation.setForeground(new java.awt.Color(255, 255, 255));
        FatherOccupation.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        FatherOccupation.setCaretColor(new java.awt.Color(255, 255, 255));
        FatherOccupation.setOpaque(true);
        FatherOccupation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FatherOccupationKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Father Occupation");

        jDateChooser1.setBackground(new java.awt.Color(51, 51, 51));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));

        Dept_err.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Dept_err.setForeground(new java.awt.Color(255, 0, 51));
        Dept_err.setText("[Mandatory]");

        Sem_err.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Sem_err.setForeground(new java.awt.Color(255, 0, 51));
        Sem_err.setText("[Mandatory]");

        Fname_err.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Fname_err.setForeground(new java.awt.Color(255, 0, 51));
        Fname_err.setText("[Mandatory]");

        LName_err.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        LName_err.setForeground(new java.awt.Color(255, 0, 51));
        LName_err.setText("[Mandatory]");

        Num_err.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Num_err.setForeground(new java.awt.Color(255, 0, 51));
        Num_err.setText("[Mandatory]");

        Dob_err.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Dob_err.setForeground(new java.awt.Color(255, 0, 51));
        Dob_err.setText("[Mandatory]");

        Gender_err.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Gender_err.setForeground(new java.awt.Color(255, 0, 51));
        Gender_err.setText("[Mandatory]");

        State_err.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        State_err.setForeground(new java.awt.Color(255, 0, 51));
        State_err.setText("[Mandatory]");

        City_err.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        City_err.setForeground(new java.awt.Color(255, 0, 51));
        City_err.setText("[Mandatory]");

        FAtherName_err.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        FAtherName_err.setForeground(new java.awt.Color(255, 0, 51));
        FAtherName_err.setText("[Mandatory]");

        FatOcc_err.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        FatOcc_err.setForeground(new java.awt.Color(255, 0, 51));
        FatOcc_err.setText("[Mandatory]");

        kButton2.setText("Delete Subject");
        kButton2.setkBackGroundColor(new java.awt.Color(204, 204, 204));
        kButton2.setkEndColor(new java.awt.Color(255, 0, 51));
        kButton2.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(102, 102, 102));
        kButton2.setkStartColor(new java.awt.Color(51, 51, 51));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Dept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(StudentID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                    .addComponent(fname)
                                    .addComponent(email)
                                    .addComponent(State)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valid, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Fname_err))
                                    .addComponent(jLabel11)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(Dob_err))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(4, 4, 4)
                                        .addComponent(valid3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(State_err))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(7, 7, 7)
                                        .addComponent(valid5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FAtherName_err))
                                    .addComponent(fatherName))
                                .addComponent(jLabel7))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dept_err))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                        .addGap(18, 29, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(9, 9, 9)
                                .addComponent(valid4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(City_err))
                            .addComponent(City)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(Gender_err)))
                                .addGap(182, 182, 182))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(7, 7, 7)
                                .addComponent(valid6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FatOcc_err))
                            .addComponent(FatherOccupation)
                            .addComponent(Semester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Opt_sub, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lname)
                            .addComponent(Number)
                            .addComponent(Gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(Sem_err))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(8, 8, 8)
                                .addComponent(valid1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LName_err))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(4, 4, 4)
                                .addComponent(valid2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Num_err)))
                        .addContainerGap(126, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(PimgX)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))))))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(96, 96, 96))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Dept_err))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fname_err)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Dob_err))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Sem_err))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Semester, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Opt_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(LName_err))
                            .addComponent(valid1, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(Num_err))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(valid2, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))
                        .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Gender_err))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(State_err))
                            .addComponent(valid3, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(City_err))
                            .addComponent(valid4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(FAtherName_err))
                            .addComponent(valid5, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(FatOcc_err))
                            .addComponent(valid6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FatherOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(PimgX, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jScrollPane1.setViewportView(kGradientPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(716, 694));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void fetchuserDetails() {
        try {
            System.out.println("Udaw34 ");
            System.out.println("Student is:  " + STUDENT_ID_main);
            myres = conn.mystmt.executeQuery("select * from student join person on student.USERID=person.USERID where STUDENT_ID = '" + STUDENT_ID_main + "'");
            while (myres.next()) {
                UserID = Integer.parseInt(myres.getString("USERID"));
                up_Name = myres.getString("NAME");
                up_email = myres.getString("Email");
                up_Number = myres.getString("MOBILE_NO");
                up_Dob = myres.getString("DOB");
                up_Gender = myres.getString("Gender");
                up_State = myres.getString("MOBILE_NO");
                up_City = myres.getString("CITY");
                up_fat_name = myres.getString("FATHER_NAME");
                up_fat_Occ = myres.getString("FATHER_OCCUPATION");
                up_Sem = myres.getString("SEMESTER");
                up_Opt_Sub = myres.getString("OPTIONAL_SUBJECT");
                input = myres.getBinaryStream("PROFILE_PIC");

                System.out.println("Date is: " + up_Dob);

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void fetchDept() {

        try {
            myres = conn.mystmt.executeQuery("select * from department");
            if (myres.getRow() <= 0) {
                int sr = 0;
                System.out.println("Fetching...");
                while (myres.next()) {
                    Dept.addItem(myres.getString("DEPARTMENT_NAME"));
                    System.out.println(myres.getString("DEPARTMENT_NAME"));
                }
            } else {
                System.out.println("No Record Found");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);

        File file = chooser.getSelectedFile();
        filename = file.getAbsolutePath();
        chk_img++;
        BufferedImage bufferedImage = null;

        try {
            bufferedImage = ImageIO.read(new File(filename));

        } catch (IOException e) {
            e.printStackTrace();
        }

        Image scaledImage = bufferedImage.getScaledInstance(PimgX.getWidth(), PimgX.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(scaledImage);
        PimgX.setIcon(image);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        if (filename == null) {
            filename = "C:\\Users\\Muneeb Ahmad\\Documents\\NetBeansProjects\\ERP\\ERP\\src\\images\\Demo_Profile.png";
        }
        if (StudentID.getText().equals("Auto Generated") || Opt_sub.getSelectedItem().equals("Select") || State.getText().equals(null) || City.getText().equals(null) || jDateChooser1 == null || fatherName.getText().equals(null) || FatherOccupation.getText().equals(null) || Number.getText().equals(null)) {
            JOptionPane.showMessageDialog(null, "Fill All Data Please!");
        } else {
            if (valid == null || valid1 == null || valid2 == null || valid3 == null || valid4 == null || valid5 == null) {
                JOptionPane.showMessageDialog(null, "Fill All Data Please!");
            } else {
                try {
                    System.out.println("1st");
                    String Stu_ID = StudentID.getText();
                    String Name = fname.getText() + " " + Lname.getText();
                    String Satte = StudentID.getText();
                    String Cityy = City.getText();
                    String Address = Satte + " " + Cityy;
                    String Number1 = Number.getText();
                    String Email = email.getText();
                    String FatherName = fatherName.getText();
                    System.out.println("2nd");
                    String FatherOccp = FatherOccupation.getText();
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String dateof = sdf.format(jDateChooser1.getDate());
                    System.out.println("date of birth is: " + dateof);
                    String Gend = (String) Gender.getSelectedItem();
                    String Role = "Student";
                    String opt_subt = (String) Opt_sub.getSelectedItem();
                    System.out.println(dateof);
                    System.out.println("3rd");
                    String Deptt = (String) Semester.getSelectedItem();
                    String numberOnly = Deptt.replaceAll("[^0-9]", "");
                    System.out.println("Sme " + Integer.parseInt(numberOnly));
                    System.out.println("sem " + numberOnly);

                    //DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-mm-dd");
                    LocalDateTime AdmDate = LocalDateTime.now();
                    String AdmDate1 = AdmDate.toString();
                    int result = 0;
                    fis = new FileInputStream(filename);
                    System.out.println("User id is: " + UserID);
                    System.out.println("FAc id is: " + STUDENT_ID_main);
                    String query = "update person set NAME='" + Name + "', MOBILE_NO='" + Number1 + "', CITY='" + Cityy + "',Email = '" + Email + "',STATE = '" + Satte + "' ,ADDRESS = '" + Address + "',DOB = '" + dateof + "' ,Gender = '" + Gend + "' where USERID='" + UserID + "'";
                    PreparedStatement pr = conn.myconn.prepareStatement(query);
                    result = pr.executeUpdate();
                    if (chk_img == 1) {
                        query = "update student set FATHER_NAME='" + FatherName + "', FATHER_OCCUPATION='" + FatherOccp + "', OPTIONAL_SUBJECT='" + opt_subt + "' , PROFILE_PIC = ? where STUDENT_ID='" + STUDENT_ID_main + "'";
                        pr = conn.myconn.prepareStatement(query);
                        pr.setBinaryStream(1, fis);
                    } else {
                        query = "update student set FATHER_NAME='" + FatherName + "', FATHER_OCCUPATION='" + FatherOccp + "', OPTIONAL_SUBJECT='" + opt_subt + "' where STUDENT_ID='" + STUDENT_ID_main + "'";
                        pr = conn.myconn.prepareStatement(query);
                    }

                    result = pr.executeUpdate();
                    System.out.println("addStudentTheoryMarks --> Update");
                    if (result == 0) {
                        myres = conn.mystmt.executeQuery("select * from person");
                        int sr = 0;
                        while (myres.next()) {
                            sr++;
                        }
                        int userID = 100 + sr + 1;

                        query = "insert into Person values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
                        pr = conn.myconn.prepareStatement(query);
                        pr.setInt(1, userID);
                        pr.setString(2, Name);
                        pr.setString(3, Number1);
                        pr.setString(4, Cityy);
                        pr.setString(5, Email);
                        pr.setString(6, "Student123*");
                        pr.setString(7, Satte);
                        pr.setString(8, Address);
                        pr.setString(9, dateof);
                        pr.setString(10, Gend);
                        pr.setString(11, Role);
                        pr.setString(12, null);
                        pr.setString(13, null);
                        pr.executeUpdate();

                        String query1 = "insert into student values(?,?,?,?,?,?,?,?,?)";
                        PreparedStatement pr1 = conn.myconn.prepareStatement(query1);
                        pr1.setString(1, Stu_ID);
                        System.out.println(1 + " " + Stu_ID);
                        pr1.setInt(2, userID);
                        System.out.println(2 + " " + userID);
                        pr1.setString(3, FatherName);
                        System.out.println(3 + " " + FatherName);
                        pr1.setString(4, FatherOccp);
                        System.out.println(4 + " " + FatherOccp);
                        pr1.setInt(5, Integer.parseInt(numberOnly));
                        System.out.println(5 + " " + Integer.parseInt(numberOnly));
                        pr1.setString(6, opt_subt);
                        System.out.println(6 + " " + opt_subt);
                        pr1.setString(7, AdmDate1);
                        //System.out.println(null);
                        pr1.setString(8, Deptcode);
                        //System.out.println(Deptcode);
                        pr1.setBinaryStream(9, fis);
                        // System.out.println(Stu_ID);
                        pr1.executeUpdate();
                        
                        query = "insert into marks values(?,?,?,?)";
                        pr = conn.myconn.prepareStatement(query);
                        pr.setString(1, Deptt);
                        pr.setString(2, null);
                        pr.setString(3, Stu_ID);
                        pr.setInt(4, 0);
                        pr.executeUpdate();
                        
                        JOptionPane.showMessageDialog(null, "Member Added Successfully");
                        
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Member Update Successfully");

                        this.dispose();
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Assigning_subject.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "SomeThing Went Wrong!");
                    //this.dispose();

                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Add_student.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Fill All Data Please!");
                } catch (NullPointerException ex) {
                    Logger.getLogger(Add_student.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Fill All Data Please!");
                } catch (IllegalArgumentException ex) {
                    Logger.getLogger(Add_student.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Enter valid Data!");
                }
            }
        }


    }//GEN-LAST:event_kButton1ActionPerformed

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_white.png")));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_red.png")));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked

        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_white.png")));
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_yellow.png")));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void maximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseExited
        maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_white.png")));
    }//GEN-LAST:event_maximizeMouseExited

    private void maximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseEntered
        maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_blue.png")));
    }//GEN-LAST:event_maximizeMouseEntered

    private void maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseClicked
        int state = this.getExtendedState();

        if (state == 0) {
            //            this.setExtendedState(Frame.MAXIMIZED_BOTH);
        } else {
            // this.setExtendedState(Frame.NORMAL);
        }
    }//GEN-LAST:event_maximizeMouseClicked

    private void DeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptActionPerformed
        if (Dept.getSelectedItem().equals("Select")) {
            String value[] = {"Select"};
            Semester.setModel(new javax.swing.DefaultComboBoxModel(value));
        } else {
            String value[] = {"Select", "Semester 1", "Semester 2", "Semester 3", "Semester 4", "Semester 5", "Semester 6", "Semester 7", "Semester 8"};
            Semester.setModel(new javax.swing.DefaultComboBoxModel(value));
        }
    }//GEN-LAST:event_DeptActionPerformed

    private void DeptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeptMouseEntered

    }//GEN-LAST:event_DeptMouseEntered

    private void DeptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeptMouseClicked

    }//GEN-LAST:event_DeptMouseClicked

    private void SemesterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SemesterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SemesterMouseClicked

    private void SemesterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SemesterMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SemesterMouseEntered

    private void SemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemesterActionPerformed
        String abc = (String) Semester.getSelectedItem();
        int StuId = 0;

        String Deptt = (String) Dept.getSelectedItem();
        String numberOnly = abc.replaceAll("[^0-9]", "");
        try {
            myres = conn.mystmt.executeQuery("select * from department where DEPARTMENT_NAME='" + Deptt + "'");
            int sr = 0;
            while (myres.next()) {
                Deptcode = myres.getString("DEPT_CODE");
            }
            System.out.println("Dept Name is:" + Deptt);
            System.out.println("Dept Code is:" + Deptcode);
            myres1 = conn.mystmt.executeQuery("select * from student where DEPT_CODE='" + Deptcode + "' and SEMESTER='" + numberOnly + "'");
            while (myres1.next()) {
                sr++;
            }
            String value[] = {"Select"};
            Opt_sub.setModel(new javax.swing.DefaultComboBoxModel(value));
            myres = conn.mystmt.executeQuery("select * from subject where DEPT_CODE='" + Deptcode + "' and SEMESTER_NO='" + numberOnly + "' and SUBJECT_TYPE='Optional'");
            while (myres.next()) {
                Opt_sub.addItem(myres.getString("SUB_NAME"));
            }
            Option_subject = (String) Opt_sub.getSelectedItem();
            StuId = 100 + sr + 1;
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        StudentID.setText(Deptcode + "-" + numberOnly + "-" + StuId);
    }//GEN-LAST:event_SemesterActionPerformed

    private void Opt_subMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Opt_subMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Opt_subMouseClicked

    private void Opt_subMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Opt_subMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Opt_subMouseEntered

    private void Opt_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opt_subActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opt_subActionPerformed

    private void GenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderMouseClicked

    private void GenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenderMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderMouseEntered

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        if (!Gender.getSelectedItem().equals("Select")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            //valid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            //valid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_GenderActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void LnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LnameFocusLost
        String name = fname.getText() + Lname.getText();
        Random x = new Random();
        int n = x.nextInt(1000);//random number 1-100
        email.setText(name.toLowerCase().replaceAll("\\s", "") + n + "@hogwards.com");
    }//GEN-LAST:event_LnameFocusLost

    private void fnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyReleased
        if (fname.getText().matches("[a-zA-Z_]+")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            valid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            valid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_fnameKeyReleased

    private void LnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LnameKeyReleased
        if (Lname.getText().matches("[a-zA-Z_]+")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            valid1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            valid1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_LnameKeyReleased

    private void NumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumberKeyReleased
        if (Number.getText().matches("[0-9]+")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            valid2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            valid2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_NumberKeyReleased

    private void StateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StateKeyReleased
        if (State.getText().matches("[a-zA-Z_]+")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            valid3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            valid3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_StateKeyReleased

    private void CityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CityKeyReleased
        if (City.getText().matches("[a-zA-Z_]+")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            valid4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            valid4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_CityKeyReleased

    private void fatherNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherNameKeyReleased
        if (fatherName.getText().matches("[a-zA-Z_]+")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            valid5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            valid5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_fatherNameKeyReleased

    private void FatherOccupationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FatherOccupationKeyReleased
        if (FatherOccupation.getText().matches("[a-zA-Z_]+")) {
            kButton1.setEnabled(true);
            kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 0));

            valid6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ok_15px.png")));
        } else {
            kButton1.setEnabled(false);
            kButton1.setkHoverEndColor(new java.awt.Color(204, 0, 0));
            kButton1.setkHoverStartColor(new java.awt.Color(204, 0, 0));
            valid6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_15px.png")));
        }
    }//GEN-LAST:event_FatherOccupationKeyReleased

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed

        try {
            System.out.println("User Id : " + UserID);
            String query = "delete from person where USERID='" + UserID + "'";
            PreparedStatement pr = conn.myconn.prepareStatement(query);
            pr.executeUpdate();
            JOptionPane.showMessageDialog(null, "Subject Deleted Successfully");
            this.dispose();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Something Went Wrong");
        }
    }//GEN-LAST:event_kButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_student.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_student.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_student.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_student.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            System.err.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error!");

        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField City;
    private javax.swing.JLabel City_err;
    private javax.swing.JComboBox<String> Dept;
    private javax.swing.JLabel Dept_err;
    private javax.swing.JLabel Dob_err;
    private javax.swing.JLabel FAtherName_err;
    private javax.swing.JLabel FatOcc_err;
    private javax.swing.JTextField FatherOccupation;
    private javax.swing.JLabel Fname_err;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JLabel Gender_err;
    private javax.swing.JLabel LName_err;
    private javax.swing.JTextField Lname;
    private javax.swing.JLabel Num_err;
    private javax.swing.JTextField Number;
    private javax.swing.JComboBox<String> Opt_sub;
    private javax.swing.JLabel PimgX;
    private javax.swing.JLabel Sem_err;
    private javax.swing.JComboBox<String> Semester;
    private javax.swing.JTextField State;
    private javax.swing.JLabel State_err;
    private javax.swing.JTextField StudentID;
    private javax.swing.JLabel close;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fatherName;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel maximize;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel valid;
    private javax.swing.JLabel valid1;
    private javax.swing.JLabel valid2;
    private javax.swing.JLabel valid3;
    private javax.swing.JLabel valid4;
    private javax.swing.JLabel valid5;
    private javax.swing.JLabel valid6;
    // End of variables declaration//GEN-END:variables
}
